name: CI Portal Solicitacoes

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: db_portal_solicitacoes
        ports:     
          - 3306:3306
    env:
        DB_URL: jdbc:mysql://127.0.0.1:3306/db_portal_solicitacoes?createDatabaseIfNotExist=true                                                                                                                       ┃
        DB_USERNAME: root                                                                                                                                                                                              ┃
        DB_PASSWORD: root 
        API_SECURITY_TOKEN_SECRET: m5CDrAYgQ5dPk1vDv2WkJMx9p5GMFGZL
        ATTEN_BOOTSTRAP_EMAIL: attendant@example.test
        ATTEN_BOOTSTRAP_PASSWORD: Senha123@
        REQ_BOOTSTRAP_EMAIL: requester@example.test
        REQ_BOOTSTRAP_PASSWORD: Senha123@
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
      - run: chmod +x mvnw && ./mvnw clean package
